# Generated by Django 3.2.20 on 2023-08-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='id товара на ozon')),
                ('name', models.CharField(max_length=500, verbose_name='название товара')),
                ('price', models.IntegerField(verbose_name='цена товара')),
                ('rating', models.FloatField(verbose_name='рейтинг товара')),
                ('comments', models.IntegerField(verbose_name='количество комментариев')),
                ('discount', models.CharField(max_length=5, verbose_name='скидка на товар')),
                ('image_url', models.CharField(max_length=500, verbose_name='ссылка на изображение')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления товара')),
            ],
            options={
                'verbose_name': 'Товар Ozon',
                'verbose_name_plural': 'Товары Ozon',
            },
        ),
    ]
